services:
  - type: web
    name: telegram-rpg-bot
    env: node
    region: frankfurt  # Или oregon, singapore, ohio
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GAME_URL
        value: https://my-telegram-game-l30583gvf-daniils-projects-0a0875d5.vercel.app